" NOTE: SETTINGS IN THIS FILE ARE HEAVILY RIPPED OFF FROM THE DP
" lots used from https://github.com/rdlugosz/dotfiles/blob/master/vimrc
set nocompatible		" be iMproved
" For some reason fs01sb started throwing fatal SSL errors for https github
" when I switched to the new dotfiles procedure, so this hack lets it work
if hostname() =~ 'alchemy'
  let g:plug_url_format = 'git@github.com:%s.git'
endif

" Plugins
call plug#begin('~/.vim/plugged')

" Vim Airline improves the look & functionality of the statusline.
Plug 'vim-airline/vim-airline' | Plug 'vim-airline/vim-airline-themes'
" Was on fs01sb config but commented out because it caused tmux/vim to hang,
" would like to debug at some point
"Plug 'edkolev/tmuxline.vim'

" Surround.vim lets you add/change/remove surrounding chars and tags
" https://github.com/tpope/vim-surround
Plug 'tpope/vim-surround'

" Provides additional text objects
Plug 'wellle/targets.vim'

" Allow vim-surround to be repeated by .
Plug 'tpope/vim-repeat'

" Commentary.vim provides commenting for many languages
" Use gcc to comment out a line (takes a count), gc to comment out the
" target of a motion (for example, gcap to comment out a paragraph),
" gc in visual mode to comment out the selection, and gc in operator
" pending mode to target a comment.
" https://github.com/tpope/vim-commentary
Plug 'tpope/vim-commentary'

" Pairs of handy bracket mappings
Plug 'tpope/vim-unimpaired'

" Add a scratch pad
Plug 'vim-scripts/scratch.vim'

" Autoclose brackets
"Plug 'MartinLafreniere/vim-PairTools'
" Can't for the life of me get vim-PairTools to work when ft = javascript.jsx,
" the period seems to throw it off. For now installing auto-pairs to be used
" specifically for javascript.jsx filetype. At some point may want to look
" into completely switching to auto-pairs if its an acceptable replacement
"Plug 'jiangmiao/auto-pairs', { 'for': 'javascript.jsx' }
Plug 'jiangmiao/auto-pairs'

" CtrlP.vim is a fuzzy file, buffer, mru, tag, etc finder.
" Open with CTRL-P, then:
"   Press <c-f> and <c-b> to cycle between modes.
"   Press <c-d> to switch to filename only search instead of full path.
"   Press <c-r> to switch to regexp mode.
" https://github.com/ctrlpvim/ctrlp.vim
Plug 'ctrlpvim/ctrlp.vim'

" ctrlp-funky adds function navigation to ctrlp
Plug 'tacahiroy/ctrlp-funky'

" Tabular.vim is a plugin that aligns text by some pattern, e.g.:
" :Tab /,
" will align lines by their commas. We have some mappings set up later, like
" <leader>t: to align on symbals and <leader>t= to align on assignment.
" https://github.com/godlygeek/tabular
Plug 'godlygeek/tabular', { 'on': ['Tabularize'] }

" Indent Guides is a plugin for visually displaying indent levels in Vim.
" Toggle with <leader>ig
" https://github.com/nathanaelkane/vim-indent-guides
Plug 'nathanaelkane/vim-indent-guides'

" Creates a new text object 'i' for indentation. E.g.,
"   vii will select block of text at current indent level
"   vai will select block of text at current indent level, plus line above
"   vaI selects block of text at current indent level, plus line above & below
" http://www.vim.org/scripts/script.php?script_id=3037
Plug 'michaeljsmith/vim-indent-object'

if version >= 800
  " Asynchronous Lint Engine
  " https://github.com/w0rp/ale
  " ALE (Asynchronous Lint Engine) is a plugin for providing linting in NeoVim
  " and Vim 8 while you edit your text files.
  Plug 'w0rp/ale'
else
  " Syntax checker for many languages
  " https://github.com/scrooloose/syntastic
  Plug 'vim-syntastic/syntastic'
  " https://github.com/pmsorhaindo/syntastic-local-eslint.vim
  Plug 'pmsorhaindo/syntastic-local-eslint.vim'
endif

" Project level configurations for tabs and new lines
" Plug 'editorconfig/editorconfig-vim', { 'for': ['javascript', 'javascript.jsx'] }
Plug 'editorconfig/editorconfig-vim'

" Searches Dash.app for the word under the cursor with <leader>d
" https://github.com/rizzatti/dash.vim
Plug 'rizzatti/dash.vim'

" Adds the :G family of commands for grepping. Automatically decides between
" Ag, Ack and Grep depending on what's available.
" https://github.com/rizzatti/greper.vim
Plug 'rizzatti/greper.vim'

" This is a dependency of Dash.vim and Grepper.vim
" https://github.com/rizzatti/funcoo.vim
Plug 'rizzatti/funcoo.vim'

if has('python') && version >= 704
  " UltiSnips - The ultimate snippet solution for Vim.
  " https://github.com/SirVer/ultisnips
  Plug 'SirVer/ultisnips'
else
  " SnipMate aims to provide support for textual snippets, similar to TextMate
  " or other Vim plugins. Activate by typing some text and hitting <tab>.
  " Snipmate depends on tlib and mw-utils.
  " https://github.com/garbas/vim-snipmate
  Plug 'tomtom/tlib_vim'
  Plug 'MarcWeber/vim-addon-mw-utils'
  Plug 'garbas/vim-snipmate'
endif
" Actual snippets
Plug 'honza/vim-snippets'
" Snippets for react
" https://github.com/justinj/vim-react-snippets
Plug 'justinj/vim-react-snippets'

if version > 703
  " Shows git diff in the gutter
  " https://github.com/airblade/vim-gitgutter
  Plug 'airblade/vim-gitgutter'
endif

" Adds git commands
Plug 'tpope/vim-fugitive' | Plug 'tpope/vim-rhubarb'

" show multipanes when editing a COMMIT_EDITMSG
Plug 'rhysd/committia.vim'

" Extended % matching for HTML and other languages
Plug 'vim-scripts/matchit.zip'

" Better visual star searching
Plug 'bronson/vim-visual-star-search'

" Highlight matching HTML tag
" Plug 'gregsexton/matchtag'

" A set of mappings for HTML, XML, PHP, ASP, eRuby, JSP, and more (formerly allml)
Plug 'tpope/vim-ragtag'

" Vim Hard mode
" Disables using hjkl multiple times in a row
" https://github.com/takac/vim-hardtime
" Plug 'takac/vim-hardtime'

" Reopen files where you left off last time
" https://github.com/dietsche/vim-lastplace
Plug 'dietsche/vim-lastplace'

" Add file manip commands like Remove, Move, Rename, SudoWrite
Plug 'tpope/vim-eunuch'

" Easier agrument wrapping
Plug 'FooSoft/vim-argwrap'

" add gS to smart split lines like comma lists and html tags
" gS to split a one-liner into multiple lines
" gJ (with the cursor on the first line of a block) to join a block into a single-line statement
Plug 'AndrewRadev/splitjoin.vim'

" Save sessions
Plug 'xolox/vim-misc' | Plug 'xolox/vim-session'

" Ask what file you wanted to open when its not a real file
Plug 'EinfachToll/DidYouMean'

" Language syntax support
Plug 'tpope/vim-markdown', { 'for': 'markdown' }
Plug 'tpope/vim-git'

" Tools and environment to make Vim superb for developing with Node.jS
" https://github.com/moll/vim-node
Plug 'moll/vim-node', { 'for': ['javascript', 'javascript.jsx'] }

" PREVIOUS JS PACKAGES START
" " Javascript Syntax Support
" Plug 'elzr/vim-json', { 'for': 'json' }
" " Plug 'pangloss/vim-javascript', { 'for': ['javascript', 'javascript.jsx']  }" Javascript Syntax
" Plug 'othree/yajs.vim', { 'for': ['javascript', 'javascript.jsx']  }" Javascript Syntax
" Plug 'gavocanov/vim-js-indent', { 'for': ['javascript', 'javascript.jsx'] } " Javascript Indenting
" Plug 'mxw/vim-jsx', { 'for': ['javascript', 'javascript.jsx'] } " JSX Support for React
" Plug 'heavenshell/vim-jsdoc', { 'for': ['javascript', 'javascript.jsx'] } "JSDoc suto-snippets
" Plug 'othree/javascript-libraries-syntax.vim', { 'for': ['javascript', 'javascript.jsx'] } " Extras for javascript Libraries
" PREVIOUS JS PACKAGES CONFIG END

" NEW JS PACKAGES CONFIG START
" javascript support still a little iffy, trying variations
" Javascript Syntax Support
Plug 'elzr/vim-json'

let s:js_mode = 'othree'
if s:js_mode ==# 'pangloss'
  " PANGLOSS MODE
  " 1.  Preferring pangloss for now since I like the included indentexpr
  "     it also has a node ftdetect, but that is the same as in
  "     moll/vim-node
  " 2.  After syntax, ftplugin, indent for JSX
  Plug 'pangloss/vim-javascript'
        \| Plug 'mxw/vim-jsx'
  let g:javascript_plugin_jsdoc = 1

elseif s:js_mode ==# 'othree'
  " YAJS MODE
  " 1.  yajs.vim highlighting is a little more robust than the pangloss one.
  " 2.  The libraries syntax adds unique highlighting for
  "     jQuery,backbone,etc. and I've confirmed it is only compatible with
  "     yajs.vim as of 2016-11-03.
  " 3.  es.next support has possible jsx indent conflicts
  "     @see https://github.com/othree/es.next.syntax.vim/issues/5
  Plug 'othree/yajs.vim'
        \| Plug 'othree/javascript-libraries-syntax.vim'
        \| Plug 'othree/es.next.syntax.vim'
        \| Plug 'mxw/vim-jsx'
endif

Plug 'gavocanov/vim-js-indent', { 'for': ['javascript', 'javascript.jsx'] } " Javascript Indenting
" <leader>pd on function to insert jsdoc above
Plug 'heavenshell/vim-jsdoc' "JSDoc suto-snippets
" NEW JS PACKAGES CONFIG END

" PHP Syntax Supoort
" https://github.com/StanAngeloff/php.vim
Plug 'StanAngeloff/php.vim'

" A collection of language packs for Vim - Probably includes most of the ones
" from above
" https://github.com/sheerun/vim-polyglot
"Plug 'sheerun/vim-polyglot'

" PHP Refactor tool
" https://github.com/adoy/vim-php-refactoring-toolbox
" Plug 'adoy/vim-php-refactoring-toolbox'

" Emoji! 😄
Plug 'junegunn/vim-emoji'

" Color schemes
Plug 'altercation/vim-colors-solarized'
"Plug 'sickill/vim-monokai'
Plug 'lbrieden21/vim-monokai'
" Plug 'jpo/vim-railscasts-theme'
Plug 'mhartington/oceanic-next'
Plug 'morhetz/gruvbox'
Plug 'sjl/badwolf'
Plug 'sheerun/vim-wombat-scheme'
" Plug 'flazz/vim-colorschemes' " literal crapload of colorschemes

" VDebug debugger
" Plug 'joonty/vdebug'

" Provides database access to many dbms (Oracle, Sybase, Microsoft, MySQL, DBI,..)
" https://github.com/vim-scripts/dbext.vim
" Plug 'vim-scripts/dbext.vim'

" Other tpope fun
" ga - Print the unicode value of the character under the cursor in decimal,
" hexadecimal and octal, along with the unicode name, HTML entity, Emoji code,
" and any available |digraphs|.
" https://github.com/tpope/vim-characterize
Plug 'tpope/vim-characterize'
" enhance CTRL-A/CTRL-X to increment dates, times, and more
" https://github.com/tpope/vim-speeddating
Plug 'tpope/vim-speeddating'
" jdaddy.vim: JSON manipulation and pretty printing
" * aj provides a text object for the outermost JSON object, array, string, number, or keyword.
" * gqaj "pretty prints" (wraps/indents/sorts keys/otherwise cleans up) the JSON construct under the cursor.
" * gwaj takes the JSON object on the clipboard and extends it into the JSON object under the cursor.
" * There are also ij variants that target innermost rather than outermost JSON construct.
" https://github.com/tpope/vim-jdaddy
Plug 'tpope/vim-jdaddy'
" obsession.vim: continuously updated session files
" https://github.com/tpope/vim-obsession
" Plug 'tpope/vim-obsession'
" tbone.vim: Basic tmux support for Vim.
" :Tmux lets you call any old tmux command (with really good tab complete).
" :Tyank and :Tput give you direct access to tmux buffers.
" :Twrite sends a chunk of text to another pane. Give an argument like windowtitle.2, top-right, or last, or let it default to the previously given argument.
" :Tattach lets you use a specific tmux session from outside of it.
" https://github.com/tpope/vim-tbone
" Plug 'tpope/vim-tbone'
" Create Git release commits and tags with changelogs
" https://github.com/tpope/git-bump
" Plug 'tpope/git-bump'

" Make vim more Puppet friendly!
" https://github.com/rodjek/vim-puppet
Plug 'rodjek/vim-puppet'

" Plugins to load on OS X only
if has("unix")
  let s:uname = system("uname -s")
  if s:uname == "Darwin\n"
    " Suggestion and Tab completion
    " Requires a locally-compiled library; see docs. Note this will work
    " fine on Linux, but disabling there since we mostly code on OS X and it
    " can be a hassle to compile the dependent libraries.
    " https://github.com/Valloric/YouCompleteMe
    "Plug 'Valloric/YouCompleteMe', { 'do': './install.py' }
    Plug 'ternjs/tern_for_vim', { 'do': 'npm install' }
    Plug 'Valloric/YouCompleteMe', { 'do': './install.py --tern-completer' }
    " set breakpoints to be able to debug vim plugins
    "Plug 'vim-scripts/genutils'
    "Plug 'albfan/vim-breakpts'
  endif
endif

call plug#end()

" Enable file type detection.
filetype plugin indent on	" required!

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" SETTINGS
" tpope/vim-sensible is inlined here & used as a baseline
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""
if has('autocmd')
  filetype plugin indent on
endif
if has('syntax') && !exists('g:syntax_on')
  syntax enable     " enable syntax processing
endif

" Turn on font that will work with powerline on macvim. At this point not sure
" why necessary
if has("gui_running")
	if has("gui_macvim")
		":set guifont=DejaVu\ Sans\ Mono\ for\ Powerline:h11
		:set guifont=Monaco\ for\ Powerline:h12
	endif
endif

" Remap auto-pairs keys if on mac
if has("gui_macvim")
  let g:AutoPairsShortcutToggle     = 'π' " <m-p>
  let g:AutoPairsShortcutFastWrap   = '∑' " <m-w>
  let g:AutoPairsShortcutJump       = '∆' " <m-j>
  let g:AutoPairsShortcutBackInsert = '∫' " <m-b>
endif

set smartindent     " make indenting better
set autoindent		" preserve indent level on newlines
set noexpandtab		" use spaces, not tabs
set tabstop=4		" a tab is 4 spaces
set shiftwidth=4	" an autoindent (with <<) is 4 spaces
set softtabstop=4	" tabwidth in insert mode
set smarttab		" use shiftwidth/tabstop based on context

set backspace=indent,eol,start " Allow backspace in insert mode

set lazyredraw      " redraw only when we need to.

" By default, complete is set to: complete=.,w,b,u,t,i
" The 'i' means 'included files' and can result in major slowdowns
set complete-=i

" Don't assume numbers starting with zero are octal
set nrformats-=octal

" Time out on key codes but not mappings.
" Basically this makes terminal Vim work sanely.
set notimeout
set ttimeout
set ttimeoutlen=10

set incsearch		" incremental searching
set hlsearch		" highlight matches
set ignorecase		" serach are case insensitive...
set smartcase		" ... unless they contain at least one capital letter

set laststatus=2	" always show the status line
set ruler			" show cursor position (overridden by statusline)
set showcmd			" show partial command in bottom-right
set showtabline=1	" Show tabline only when more than one tab exists
set title           " Show the filename in the window titlebar

set wildmenu 		" use tab completion on command line

" Better tab completion
set wildmode=longest,list

set showmatch		" Show the matching brace

" force error bells off - may not work on normal vim or linux
set vb t_vb=

" Controls the number of lines/chars to keep visible before scrolling
set scrolloff=3
set sidescrolloff=10
set sidescroll=1
set display+=lastline " show the last line that fits in window (vs '@@@@')

if &encoding ==# 'latin1' && has('gui_running')
  set encoding=utf-8
endif

" Changes what Vim displays for special chars like trailing space & tabs
set nolist " Don't show invisible characters
" let &listchars = "tab:>-,trail:\u2591,extends:>,precedes:<,nbsp:\u00b7"
let &listchars = "tab:|\ ,trail:\u2591,extends:>,precedes:<,nbsp:\u00b7"

" The semicolon will cause Vim to search back (up) in the directory tree
if has('path_extra')
  setglobal tags-=./tags tags^=./tags;
endif

set autoread 			" reload unchanged buffers when file changed outside vim
set fileformats+=mac	" should already be the default when compiled on mac

" remember more than 20 previous search/commands
if &history < 1000
  set history=1000
endif

" max number of tab page that can be opened
if &tabpagemax < 50
  set tabpagemax=50
endif

" Control what is preserved in the viminfo file
"   ! save and restore all-caps-named GLOBAL variables
"   ' number of files for which we should remember marks
"   < maximum line count of a register that is saved
"   s maximum byte count of a register that is saved
"   h disable the hlsearch when loading viminfo
"   no '/' specified means use value of 'history' for saving searches
"   no ':' specified means use value of 'history' for command line history
"   no '%' specified means don't save/reload the buffer list
"   no 'n<file>' specified means use default location for .viminfo
set viminfo=!,'100,<1000,s100,h

set sessionoptions-=options " exclude options from the :mksession command

" Load matchit.vim, but only if the user hasn't installed a newer version.
" Makes the % command jump to matching HTML tags, if/else/endif in Vim scripts, etc.
if !exists('g:loaded_matchit') && findfile('plugin/matchit.vim', &rtp) ==# ''
  runtime! macros/matchit.vim
endif

" Set colorscheme
" Allow color schemes to do bright colors without forcing bold.
if &t_Co == 8 && $TERM !~# '^linux'
  set t_Co=16
endif
if $TERM =~ "-256color"
  set t_Co=256
endif
set background=dark
" silent! colorscheme solarized
" let g:airline_theme='solarized'		" Colors for vim-airline
" silent! colorscheme monokai
" let g:airline_theme='molokai'
" silent! colorscheme OceanicNext
" let g:airline_theme='oceanicnext'
silent! colorscheme gruvbox
let g:airline_theme='gruvbox'
" silent! colorscheme badwolf
" let g:airline_theme='badwolf'
" silent! colorscheme wombat
" let g:airline_theme='wombat'

" Allow gx to open urls in the browser
let g:netrw_browsex_viewer = 'open'

" Centralize backups, swapfiles and undo history
set swapfile
set directory=~/.vim/swaps//
set backup
set backupdir=~/.vim/backups//
if has('persistent_undo')
  if exists("&undodir")
    set undofile
    set undodir=~/.vim/undo//
    set undoreload=10000
  endif
endif
set undolevels=10000

" Resize splits when the window is resized
au VimResized * :wincmd =

" Use relative line numbers
if exists("&relativenumber")
  set relativenumber
  autocmd BufReadPost * set relativenumber
endif

" Line numbers
set number

" Prevent Vim from clobbering the scrollback buffer. See
" http://www.shallowsky.com/linux/noaltscreen.html
"set t_ti= t_te=

set nowrap        " don't wrap lines (we map leader-W to toggle)
set linebreak     " when wrapping, wrap at word boundaries (vs last char)
if exists('+breakindent')
	set breakindent " preserves the indent level of wrapped lines
	set showbreak=↪ " illustrate wrapped lines
	set wrap        " wrapping with breakindent is tolerable
endif
" When on first/last char in a line, allow left/right to navigate
" through to the prev/next line.
set whichwrap+=<,>,h,l

set foldenable          " enable folding
set foldlevelstart=10   " open most folds by default
set foldnestmax=10      " 10 nested fold max
set foldmethod=indent   " fold based on indent level

" Create new splits to the right and below
set splitright
set splitbelow

" allow modified buffers to be hidden
set hidden

" exclusions from the autocomplete menu
set wildignore+=*/tmp/*,*/node_modules/*

" mouse works in most terminal software we use...
set mouse=a

" change the cursor shape depending on mode
" see: http://vim.wikia.com/wiki/Change_cursor_shape_in_different_modes
if exists('$TMUX') && hostname() == 'fs01sb.dfw.alchemysystems.com'
  let &t_SI = "\<Esc>[3 q"
  let &t_EI = "\<Esc>[0 q"
elseif exists('$TMUX')
  let &t_SI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=1\x7\<Esc>\\"
  let &t_EI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=0\x7\<Esc>\\"
else
  let &t_SI = "\<Esc>]50;CursorShape=1\x7"
  let &t_EI = "\<Esc>]50;CursorShape=0\x7"
endif

" highlight current line
"set cursorline

" Set up vertical ruler at 80 characters in
" if exists('+colorcolumn')
"   set colorcolumn=100
" endif

" Don't try to highlight lines longer than 800 characters.
set synmaxcol=800

" Vim-session Config
let g:session_autosave = 'yes'
let g:session_autosave_to = 'default'
let g:session_autosave_periodic = 5
let g:session_autosave_silent = 1
" let g:session_verbose_messages = 1
" let g:session_autoload = 'yes'

" vim-json config
let g:vim_json_syntax_conceal = 0

" YouCompleteMe Config
let g:ycm_collect_identifiers_from_tags_files = 1
let g:ycm_seed_identifiers_with_syntax = 1
let g:ycm_autoclose_preview_window_after_completion = 1
let g:ycm_autoclose_preview_window_after_insertion = 1
" Remove <TAB> because it conflicts with Snipmate
" Note that it's easier to navigate the suggestions with C-n/C-p anyway
let g:ycm_key_list_select_completion   = ['<C-j>', '<C-n>', '<Down>']
let g:ycm_key_list_previous_completion = ['<C-k>', '<C-p>', '<Up>']

" UltiSnips config
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<tab>"
let g:UltiSnipsJumpBackwardTrigger="<s-tab>"

" easier emojis!
set completefunc=emoji#complete
vnoremap <c-e> :s/:\([^:]\+\):/\=emoji#for(submatch(1), submatch(0))/<CR>:nohlsearch<CR>:redraw!<CR>

" Argwrap config
nnoremap <silent> <leader>A :ArgWrap<CR>
let g:argwrap_tail_comma = 1

" Gitgutter config
if exists('&signcolumn')
  set signcolumn=yes
else
  let g:gitgutter_sign_column_always = 1
endif

" ALE linter config
" let g:ale_sign_column_always = 1
let g:ale_sign_error = '✗'
let g:ale_sign_warning = '⚠'
" let g:ale_php_phpcs_standard = 'PSR2'
let g:ale_php_phpcs_standard = 'phpcs.xml'
" let g:ale_php_phpcs_standard = '/web/lbriedendev.com/git/ets/www/phpcs.xml'
" let g:ale_php_phpcs_use_global = 1
" let g:ale_php_phpcs_executable = 'phpcs -a --standard=phpcs.xml'
" let g:ale_fixers = []
" let g:ale_fixers.javascript = ['eslint']
" Turn on all php linters except phpcs and phpmd
let g:ale_linters = {
\   'php': ['hack', 'langserver', 'php', 'phpstan'],
\}
" Unless we are in api or phpunit directories, then turn on ones we actually use
let g:ale_pattern_options = {
\   'www/.\+/\(api\|phpunit\|codeception-new\)/.\+\.phph\?$': {
\       'ale_linters': {'php': ['php', 'phpcs', 'phpmd']},
\   },
\}

" Syntastic config
let g:syntastic_enable_signs = 1 " check if this slows things down
let g:syntastic_check_on_open = 1
let g:syntastic_error_symbol = '✗'
let g:syntastic_warning_symbol = '⚠'
let g:syntastic_auto_jump = 0
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_javascript_checkers = ['eslint']
"let g:syntastic_php_phpcs_args="--standard=PSR2"
let g:puppet_module_detect=1
let g:syntastic_puppet_puppetlint_args = "--no-80-chars-check --no-class_inherits_from_params_class-check"
let g:syntastic_mode_map = { 'mode': 'active',
  \ 'active_filetypes': ['javascript', 'python', 'perl', 'sh', 'puppet'],
  \ 'passive_filetypes': ['html','php'] }

" editorconfig config
let g:EditorConfig_exclude_patterns = ['fugitive://.*']

" JSDoc config
let g:jsdoc_enable_es6 = 1

" vim-jsx config
let g:jsx_ext_required = 0

" ctrlp config
let g:ctrlp_map = '<Leader>t'
let g:ctrlp_working_path_mode = 'w'
"let g:ctrlp_working_path_mode = 'c'
let g:ctrlp_custom_ignore = {
	\ 'dir':  '\v[\/]\.(git|hg|svn)$|[\/]node_modules',
	\ 'file': '\v\.(exe|so|dll)$',
	\ 'link': 'SOME_BAD_SYMBOLIC_LINKS',
	\ }
"let g:ctrlp_custom_ignore = '\v\~$|\.(o|swp|pyc|wav|mp3|ogg|blend)$|(^|[/\\])\.(hg|git|bzr|svn)($|[/\\])|__init__\.py|*node_modules*'
let g:ctrlp_show_hidden = 0
let g:ctrlp_switch_buffer = 0
let g:ctrlp_clear_cache_on_exit = 0
" Use The Silver Searcher if available
if executable('ag')
	" Use ag in CtrlP
	let g:ctrlp_user_command = 'ag %s -l --nocolor --ignore node_modules --ignore vendor --ignore logs --ignore _output --ignore ciJReports --ignore *.map --ignore *.sql --hidden -g "" --depth 15'

	" Skip caching since ag is so fast
	let g:ctrlp_use_caching = 0
endif

" ctrlp-funky config
nnoremap <Leader>fu :CtrlPFunky<Cr>
" narrow the list down with a word under cursor
nnoremap <Leader>fU :execute 'CtrlPFunky ' . expand('<cword>')<Cr>
let g:ctrlp_funky_nudists = [ 'php' ]

" Greper config
nmap <silent> <leader>a <Plug>GreperBangWord

" highlight trailing whitespace
highlight ExtraWhitespace ctermbg=red guibg=red
autocmd BufWinEnter * match ExtraWhitespace /\s\+$/
match ExtraWhitespace /\s\+$/
autocmd BufWinEnter * match ExtraWhitespace /\s\+$/
autocmd InsertEnter * match ExtraWhitespace /\s\+\%#\@<!$/
autocmd InsertLeave * match ExtraWhitespace /\s\+$/
autocmd BufWinLeave * call clearmatches()

" Scratch
command! ScratchToggle call ScratchToggle()

function! ScratchToggle()
    if exists("w:is_scratch_window")
        unlet w:is_scratch_window
        exec "q"
    else
        exec "normal! :Sscratch\<cr>\<C-W>L"
        let w:is_scratch_window = 1
    endif
endfunction

nnoremap <silent> <leader><tab> :ScratchToggle<cr>

" hardmode config
" let g:hardtime_default_on = 1
" let g:hardtime_timeout = 750
" let g:hardtime_ignore_quickfix = 1
" let g:hardtime_allow_different_key = 1
" let g:hardtime_maxcount = 2
" let g:list_of_normal_keys = ['h','j','k','l','-','+']

" Vdebug settings
" if hostname() == 'fs01sb.dfw.alchemysystems.com'
" 	let g:vdebug_options = {
" 		\	"port" : 9511,
" 		\	"timeout" : 60,
" 		\	"path_maps" : {"/web" : "/export/web"},
" 		\	"break_on_open" : 1,
" 		\	"continuous_mode" : 0,
" 	\}
" else
" 	let g:vdebug_options = {
" 		\	"timeout" : 30,
" 		\	"break_on_open" : 1,
" 		\	"continuous_mode" : 0,
" 	\}
" endif

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" STATUS LINE (won't see much unless we disable Airline)
" see: :help 'statusline
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" status bar
"set statusline=%F%m%r%h%w\  "fullpath and status modified sign
set statusline=%f%m%r%h%w\  "path and status modified sign
set statusline+=\ %y "filetype
set statusline+=%=
set statusline+=\ [%l\/%L:\%v] "line number and column number

" Airline.vim customizations
" Use the poweline fonts to make airline pretty
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1

"""""""""""""""""""""""""""""""""""""""""""""""""""""""
" MAPPINGS
"""""""""""""""""""""""""""""""""""""""""""""""""""""""
" :map       Normal, Visual and Operator-pending
" :vmap      Visual
" :nmap      Normal
" :omap      Operator-pending (Eg: dw where d is operator character and w is motion character)
" :map!      Insert and Command-line
" :imap      Insert
" :cmap      Command-line
"
" Quick ESC
" Some people map jk for this, but it makes Dijkstra sad.
" imap kj <ESC>
imap jj <ESC>

" Insert the hashrocket with CTRL+l
inoremap <c-l> <space>=><space>

" map j to gj and k to gk, so line navigation ignores line wrap
" ...but only if the count is undefined (otherwise, things like 4j
" break if wrapped LINES are present)
nmap <expr> j (v:count == 0 ? 'gj' : 'j')
nmap <expr> k (v:count == 0 ? 'gk' : 'k')

" Navigate splits more easily
nmap <C-h> <C-w>h
nmap <C-j> <C-w>j
nmap <C-k> <C-w>k
nmap <C-l> <C-w>l

noremap <leader>v <C-w>v

" List navigation
nnoremap <left>  :cprev<cr>zvzz
nnoremap <right> :cnext<cr>zvzz
nnoremap <up>    :lprev<cr>zvzz
nnoremap <down>  :lnext<cr>zvzz

" Key repeat hack for resizing splits, i.e., <C-w>+++- vs <C-w>+<C-w>+<C-w>-
" see: http://www.vim.org/scripts/script.php?script_id=2223
nmap <C-w>+ <C-w>+<SID>ws
nmap <C-w>- <C-w>-<SID>ws
nmap <C-w>> <C-w>><SID>ws
nmap <C-w>< <C-w><<SID>ws
nnoremap <script> <SID>ws+ <C-w>+<SID>ws
nnoremap <script> <SID>ws- <C-w>-<SID>ws
nnoremap <script> <SID>ws> <C-w>><SID>ws
nnoremap <script> <SID>ws< <C-w><<SID>ws
nmap <SID>ws <Nop>

" Tab handling
nnoremap <leader>( :tabprev<cr>
nnoremap <leader>) :tabnext<cr>
nnoremap <C-t> :tabnew<CR>
"nnoremap <C-j> :tabprevious<CR>
"nnoremap <C-k> :tabnext<CR>
inoremap <C-t> <Esc>:tabnew<CR>
"inoremap <C-j> <Esc>:tabprevious<CR>i
"inoremap <C-k> <Esc>:tabnext<CR>i

" Allow writing via sudo
cnoremap w!! w !sudo tee > /dev/null %

" Make crl-a work in command mode
cnoremap <c-a> <home>
cnoremap <c-e> <end>

" Allow for some common quit/write cmd typos
command! Q q " Bind :Q to :q
command! W w " Bind :W to :w
command! Qall qall

" gv reselects the last visual selection, however doesn't work correctly after
" cut/paste, so next command
" Visually select the text that was last edited/pasted
nmap gV `[v`]

" reselect visual block after indent/outdent
vnoremap < <gv
vnoremap > >gv

" allow the . to execute once for each line of a visual selection
vnoremap . :normal .<CR>

" move selected lines up or down
" vnoremap <C-j> :m '>+1<CR>gv=gv
" vnoremap <C-k> :m '<-2<CR>gv=gv
" more advanced way of moving lines/selections up or down - accepts number of
" times to execute command
function! MoveLineUp()
  call MoveLineOrVisualUp(".", "")
endfunction

function! MoveLineDown()
  call MoveLineOrVisualDown(".", "")
endfunction

function! MoveVisualUp()
  call MoveLineOrVisualUp("'<", "'<,'>")
  normal gv
endfunction

function! MoveVisualDown()
  call MoveLineOrVisualDown("'>", "'<,'>")
  normal gv
endfunction

function! MoveLineOrVisualUp(line_getter, range)
  let l_num = line(a:line_getter)
  if l_num - v:count1 - 1 < 0
    let move_arg = "0"
  else
    let move_arg = a:line_getter." -".(v:count1 + 1)
  endif
  call MoveLineOrVisualUpOrDown(a:range."move ".move_arg)
endfunction

function! MoveLineOrVisualDown(line_getter, range)
  let l_num = line(a:line_getter)
  if l_num + v:count1 > line("$")
    let move_arg = "$"
  else
    let move_arg = a:line_getter." +".v:count1
  endif
  call MoveLineOrVisualUpOrDown(a:range."move ".move_arg)
endfunction

function! MoveLineOrVisualUpOrDown(move_arg)
  let col_num = virtcol(".")
  execute "silent! ".a:move_arg
  execute "normal! ".col_num."|"
endfunction

vnoremap <silent> <C-k> :<C-u>call MoveVisualUp()<CR>
vnoremap <silent> <C-j> :<C-u>call MoveVisualDown()<CR>
" normal mode affects horizontal splits or being able to move to CtrlP or
" Greper quickfix or location windows opened in split below
" nnoremap <silent> <C-k> :<C-u>call MoveLineUp()<CR>
" nnoremap <silent> <C-j> :<C-u>call MoveLineDown()<CR>
" Reindent line/selection after move
" nnoremap <silent> <C-k> :<C-u>call MoveLineUp()<CR>==
" nnoremap <silent> <C-j> :<C-u>call MoveLineDown()<CR>==
" vnoremap <silent> <C-k> :<C-u>call MoveVisualUp()<CR>=gv
" vnoremap <silent> <C-j> :<C-u>call MoveVisualDown()<CR>=gv
" END LINE MOVEMENT

" Back to the buffer we came from
nmap <C-e> :e#<CR>

" Easy bouncing buffers
nmap <C-n> :bnext<CR>
nmap <C-p> :bprev<CR>

" Open tag in vertical split
map <C-\> :vs <CR>:exec("tag ".expand("<cword>"))<CR>

" Clear search string to remove highlighting
nnoremap <silent> \\ :nohlsearch<CR>

"""""""""""""""""""""""""""""""""""""""""""""""""""""""
" LEADER MAPPINGS
"""""""""""""""""""""""""""""""""""""""""""""""""""""""
" let spacebar double as our leader, for great justice
let mapleader = " " " <space>
let maplocalleader = "\\"
" nmap <space> <leader>
" xmap <space> <leader>
" nmap <space><space> <leader><leader>
" xmap <space><space> <leader><leader>

" xmap includes Visual mode but not Select mode (which we don't often use, but
" if we did we'd expect hitting space to replace the selected text with a
" space char).
" xmap <space> <leader>

" Reload our .vimrc
nmap <leader>~ :source ~/.vimrc<CR>:redraw!<CR>:AirlineRefresh<CR>:echo "~/.vimrc reloaded!"<CR>

" Open our .vimrc
nmap <Leader>~~ :e $MYVIMRC<CR>

" Open file
nmap <leader>o :CtrlP<CR>

" Open buffer
nmap <leader>; :CtrlPBuffer<CR>

" Write file
"nmap <leader>w :w<CR>

" Delete buffer
nmap <leader>q :bd<CR>

" Hide buffer
nmap <leader>Q :hide<CR>

" Toggle spelling
nmap <leader>s :set invspell<CR>:set spell?<CR>

" Fix Spelling
nnoremap <Leader>fs 1z=

" Toggle wrap
nmap <leader>W :set invwrap<CR>:set wrap?<CR>

" Open/closes folds
nnoremap <leader>z za

" Toggle background dark/light with <leader>B
function! RD_ToggleBackground()
  if &background == "dark"
    let &background = "light"
    let _snark = "Hey, wake up!!"
  else
    let &background = "dark"
    let _snark = "Who turned out the lights???"
  endif

  if exists(':Airline')
    AirlineRefresh
  endif
  redraw
  echo _snark
endfunction
nmap <silent> <leader>B :call RD_ToggleBackground()<CR>

" Toggle paste mode
set pastetoggle=<F2>

" upper/lower word
" (set a mark, visually select inner word, u/U, return to mark)
nmap <leader>U m`gUiw``
nmap <leader>L m`guiw``

" Reindent the entire file
nmap <leader>= gg=G``:echo "reindent global"<CR>

" Toggle match highlight
nmap <leader>l :set invhlsearch<CR>

" Highlight matches when jumping to next
function! HLNext (blinktime)
  highlight WhiteOnRed ctermfg=white ctermbg=red
  let [bufnum, lnum, col, off] = getpos('.')
  let matchlen = strlen(matchstr(strpart(getline('.'),col-1),@/))
  let target_pat = '\c\%#'.@/
  let ring = matchadd('WhiteOnRed', target_pat, 101)
  redraw
  exec 'sleep ' . a:blinktime . 'm'
  call matchdelete(ring)
  redraw
endfunction
" Now, remap n/N so they call themselves, center screen & call HLNext
nnoremap <silent> n nzz:call HLNext(300)<cr>
nnoremap <silent> N Nzz:call HLNext(300)<cr>

" Tabular.vim
nnoremap <Leader>t= :Tabularize assignment<CR>
vnoremap <Leader>t= :Tabularize assignment<CR>
nnoremap <Leader>t: :Tabularize symbol<CR>
vnoremap <Leader>t: :Tabularize symbol<CR>
nnoremap <Leader>t, :Tabularize comma<CR>
vnoremap <Leader>t, :Tabularize comma<CR>
nnoremap <Leader>t/ :Tabularize / \/\/<CR>
vnoremap <Leader>t/ :Tabularize / \/\/<CR>
nnoremap <Leader>t> :Tabularize /=>/<CR>
vnoremap <Leader>t> :Tabularize /=>/<CR>
nnoremap <Leader>t# :Tabularize /#/<CR>
vnoremap <Leader>t# :Tabularize /#/<CR>

" Toggle numbers
nmap <leader>n :setlocal number!<CR><bar>:setlocal relativenumber!<CR>

" Mac OS X-only mappings
if has("unix")
  let s:uname = system("uname -s")
  if s:uname == "Darwin\n"
    " Set clipboard to system clipboard
    set clipboard=unnamed
    " Search for word under cursor in Dash.app
    nmap <leader>d <Plug>DashSearch
    nmap <leader>D <Plug>DashGlobalSearch

    " Use Marked.app to preview Markdown files...
    " http://stackoverflow.com/questions/9212340/is-there-a-vim-plugin-for-preview-markdown-file
    function! s:setupMarkup()
      nmap <leader>M :silent !open -a Marked.app '%:p'<CR>:redraw!<CR>
    endfunction
    autocmd BufRead,BufNewFile *.{md,markdown,mdown,mkd,mkdn} call s:setupMarkup()
  endif
endif

" Open new vertical split
noremap <leader>v <C-w>v

" unmap F1 - stupid help key
inoremap <F1> <ESC>
nnoremap <F1> <ESC>
vnoremap <F1> <ESC>

"""""""""""""""""""""""""""""""""""""""""""""""""""""""
" FILE TYPES
"""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Some file types should wrap their text
function! RD_SetupWrapping()
  setlocal wrap
  setlocal linebreak
  setlocal textwidth=78
  setlocal nolist
endfunction

" Make sure all markdown files have the correct filetype set and setup wrapping
augroup markdown
  autocmd!
  autocmd BufRead,BufNewFile *.{md,markdown,mdown,mkd,mkdn,txt} setf markdown
  autocmd FileType markdown call RD_SetupWrapping()
  autocmd FileType markdown setlocal ts=4 sts=4 sw=4
augroup END

" enable spell checking on certain files
augroup Spelling
  autocmd!
  autocmd BufNewFile,BufRead COMMIT_EDITMSG set spell
augroup END

augroup vagrant
  autocmd!
  autocmd BufRead,BufNewFile Vagrantfile set filetype=ruby
augroup END

" Javascript
augroup ft_javascript
    au!
    " Prettify a hunk of JSON with <localleader>p
    au FileType javascript nnoremap <buffer> <localleader>p ^vg_:!python -m json.tool<cr>
    au FileType javascript vnoremap <buffer> <localleader>p :!python -m json.tool<cr>
augroup END

" }}}

" Vim
augroup ft_vim
    au!

    au FileType vim setlocal foldmethod=marker keywordprg=:help
    au FileType help setlocal textwidth=78
    au BufWinEnter *.txt if &ft == 'help' | wincmd L | endif
augroup END

" Handle SISTEM Managers crazy file types
augroup Manager
  autocmd!
  autocmd BufNewFile,BufRead *.phph set filetype=php
  autocmd BufNewFile,BufRead *.php3 set filetype=php
  "autocmd BufNewFile,BufRead *.html set filetype=php
  autocmd BufNewFile,BufRead *.phtml set filetype=php
  autocmd BufNewFile,BufRead *.rgt setf rgt
  autocmd BufNewFile,BufRead *.cir set filetype=xml
  autocmd BufNewFile,BufRead *.jrxml set filetype=xml
augroup END

" These settings I think will ultimately be handled by editorconfig, applying
" globally for now
autocmd BufNewFile,BufRead *.js set ft=javascript
autocmd BufNewFile,BufRead *.json set ft=javascript
"autocmd BufNewFile,BufRead *.jsx set ft=javascript
autocmd BufNewFile,BufRead *.css set ft=javascript
"au FileType html,php,javascript,sql,perl,rgt,c,smarty setlocal list
"au FileType javascript,javascript.jsx,json,css setlocal tabstop=2 expandtab shiftwidth=2 softtabstop=2
au FileType php,javascript,sql,perl,rgt,c,smarty setlocal list
au FileType javascript,javascript.jsx,json,css,html setlocal tabstop=2 expandtab shiftwidth=2 softtabstop=2

" vim-fugitive bindings
" Each time you open a git object using fugitive it creates a new buffer. This
" means that your buffer listing can quickly become swamped with fugitive
" buffers.Here’s an autocommand that prevents this from becomming an issue:
autocmd BufReadPost fugitive://* set bufhidden=delete
" The tree buffer makes it easy to drill down through the directories of your
" git repository, but it’s not obvious how you could go up a level to the
" parent directory. Running the following command will open the parent tree:
" :edit %:h
autocmd User fugitive
  \ if fugitive#buffer().type() =~# '^\%(tree\|blob\)$' |
  \   nnoremap <buffer> .. :edit %:h<CR> |
  \ endif

" HACK to make ale only use phpcs when in ETS clean directories
" au BufNewFile,BufRead */templates/*.php set g:ale_php_phpcs_standard=path/to/rules.xml

" vim:set ft=vim et sw=2:
