# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

[ -n "$PS1" ] && source ~/.bash_profile

# run powerline if installed - it will handle prompt
# maybe needs better configuring, not crazy about default display, plus really slow
# if command -v powerline-daemon > /dev/null; then
# 	powerline-daemon -q
# 	POWERLINE_BASH_CONTINUATION=1
# 	POWERLINE_BASH_SELECT=1
# 	. /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/powerline/bindings/bash/powerline.sh
# elif [ -f ~/.bash_prompt ]; then
#if [ -f ~/.bash_prompt ]; then
#	. ~/.bash_prompt
#	# . ~/.bash-powerline.sh
#else
#	export PS1='\w\n\u@\h$ '
#fi

