# .bashrc
# Main interactive shell configuration.
# Sourced directly by non-login interactive shells (Linux GUI terminals,
# subshells, su) and indirectly by login shells via .bash_profile.

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# If not running interactively, stop here
[[ $- != *i* ]] && return

# Load the shell dotfiles:
# * ~/.extra can be used for settings you don't want to commit.
for file in ~/dotfiles/bash/{bash_prompt,path,exports,aliases,functions}; do
	[ -r "$file" ] && source "$file"
done
unset file

# bash completion
if type brew &>/dev/null; then
	HOMEBREW_PREFIX="$(brew --prefix)"
	if [[ -r "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh" ]]; then
		source "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh"
	else
		for COMPLETION in "${HOMEBREW_PREFIX}/etc/bash_completion.d/"*; do
		  [[ -r "${COMPLETION}" ]] && source "${COMPLETION}"
		done
	fi
elif type port >/dev/null 2>/dev/null && [ -f /opt/local/etc/profile.d/bash_completion.sh ]; then
	source /opt/local/etc/profile.d/bash_completion.sh
elif [ -f /etc/bash_completion ]; then
	source /etc/bash_completion
elif [ -f /etc/profile.d/bash-completion ]; then
	source /etc/profile.d/bash-completion
elif [ -f /etc/profile.d/bash_completion.sh ]; then
	source /etc/profile.d/bash_completion.sh
elif [ -f /usr/local/etc/bash_completion ]; then
	source /usr/local/etc/bash_completion
fi

# fzf via git install
if [ -e $HOME/.fzf/shell/completion.bash ]; then
  set -o vi
  source $HOME/.fzf/shell/key-bindings.bash
  source $HOME/.fzf/shell/completion.bash
fi

## fzf + ag configuration
if command -v fzf > /dev/null && command -v ag > /dev/null; then
  export FZF_DEFAULT_COMMAND='ag --nocolor -g ""'
  export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
  export FZF_ALT_C_COMMAND="fd --type d"
  export FZF_DEFAULT_OPTS='
  --color dark,hl:33,hl+:37,fg+:235,bg+:136,fg+:254
  --color info:254,prompt:37,spinner:108,pointer:235,marker:235
  '
fi

# pyenv setup
if command -v pyenv >/dev/null; then
	export PYENV_ROOT="$HOME/.pyenv"
	export PATH="$PYENV_ROOT/bin:$PATH"
	eval "$(pyenv init -)"
fi

[ -r ~/.extra ] && source ~/.extra

test -e ${HOME}/.iterm2_shell_integration.bash && source ${HOME}/.iterm2_shell_integration.`basename $SHELL`

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

