# Add `~/bin` to the `$PATH`
PATH="$HOME/bin:$PATH"
# Load the shell dotfiles, and then some:
# * ~/.path can be used to extend `$PATH`.
# * ~/.extra can be used for other settings you don’t want to commit.
for file in ~/dotfiles/bash/{bash_prompt,path,dir_colors,exports,aliases,functions}; do
	[ -r "$file" ] && source "$file"
done
unset file

#if test -f ~/.gnupg/.gpg-agent-info -a -n "$(pgrep gpg-agent)"; then
#  source ~/.gnupg/.gpg-agent-info
#  export GPG_AGENT_INFO
#else
#  eval $(gpg-agent --daemon)
#fi

# run powerline if installed
#if command -v powerline-daemon > /dev/null; then
#    powerline-daemon -q
#    POWERLINE_BASH_CONTINUATION=1
#    POWERLINE_BASH_SELECT=1
#    #. /usr/local/lib/python3.6/site-packages/powerline/bindings/bash/powerline.sh
#	. /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/powerline/bindings/bash/powerline.sh
#fi

# fzf via Homebrew
#if [ -e /usr/local/opt/fzf/shell/completion.bash ]; then
#  source /usr/local/opt/fzf/shell/key-bindings.bash
#  source /usr/local/opt/fzf/shell/completion.bash
#fi
#
## fzf + ag configuration
#if command -v fzf > /dev/null && command -v ag > /dev/null; then
#  export FZF_DEFAULT_COMMAND='ag --nocolor -g ""'
#  export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
#  export FZF_ALT_C_COMMAND="$FZF_DEFAULT_COMMAND"
#  export FZF_DEFAULT_OPTS='
#  --color dark,hl:33,hl+:37,fg+:235,bg+:136,fg+:254
#  --color info:254,prompt:37,spinner:108,pointer:235,marker:235
#  '
#fi

test -e ${HOME}/.iterm2_shell_integration.bash && source ${HOME}/.iterm2_shell_integration.`basename $SHELL`
